import type {
  BoardPost,
  BoardSection,
  BoardSummary,
  Classroom,
} from "./types";

export const classrooms: Classroom[] = [
  {
    id: "4a-physics",
    name: "4A Physics",
    description: "Experiments, observations and evidence",
    role: "owner",
    canManage: true,
    boardCount: 3,
    postCount: 86,
    accent: "copper",
  },
  {
    id: "4b-physics",
    name: "4B Physics",
    description: "Practical work and visual explanations",
    role: "view only",
    canManage: false,
    boardCount: 2,
    postCount: 54,
    accent: "moss",
  },
  {
    id: "5a-science",
    name: "5A Science",
    description: "Field notes from the world around us",
    role: "owner",
    canManage: true,
    boardCount: 4,
    postCount: 112,
    accent: "ink",
  },
];

export const boards: BoardSummary[] = [
  {
    id: "forces-in-action",
    classId: "4a-physics",
    sortOrder: 0,
    title: "Forces in action",
    description: "Photograph a real example of a force and explain what is happening.",
    status: "active",
    allowPosting: true,
    allowComments: true,
    postCount: 24,
    commentCount: 38,
    contributorCount: 21,
    updatedLabel: "Active 8 min ago",
  },
  {
    id: "energy-transfers",
    classId: "4a-physics",
    sortOrder: 1,
    title: "Energy transfers",
    description: "Trace where energy begins and where it goes.",
    status: "active",
    allowPosting: false,
    allowComments: true,
    postCount: 31,
    commentCount: 55,
    contributorCount: 27,
    updatedLabel: "Yesterday",
  },
  {
    id: "momentum-gallery",
    classId: "4a-physics",
    sortOrder: 2,
    title: "Momentum gallery",
    description: "A visual review from last term.",
    status: "archived",
    allowPosting: false,
    allowComments: false,
    postCount: 31,
    commentCount: 42,
    contributorCount: 25,
    updatedLabel: "Archived 12 Jun",
  },
  {
    id: "forces-4b",
    classId: "4b-physics",
    sortOrder: 0,
    title: "Forces around school",
    description: "Find balanced and unbalanced forces around campus.",
    status: "active",
    allowPosting: true,
    allowComments: true,
    postCount: 28,
    commentCount: 34,
    contributorCount: 23,
    updatedLabel: "Active 21 min ago",
  },
  {
    id: "light-and-shadow",
    classId: "5a-science",
    sortOrder: 0,
    title: "Light & shadow walk",
    description: "Capture evidence of reflection, refraction or shadow.",
    status: "active",
    allowPosting: true,
    allowComments: true,
    postCount: 36,
    commentCount: 61,
    contributorCount: 29,
    updatedLabel: "Active now",
  },
];

export const sections: BoardSection[] = [
  {
    id: "push-pull",
    boardId: "forces-in-action",
    title: "Push & pull",
    note: "Look for contact forces in everyday objects.",
    sortOrder: 0,
  },
  {
    id: "friction",
    boardId: "forces-in-action",
    title: "Friction",
    note: "Show where surfaces resist movement.",
    sortOrder: 1,
  },
  {
    id: "action-reaction",
    boardId: "forces-in-action",
    title: "Action & reaction",
    note: "Pairs of forces acting in opposite directions.",
    sortOrder: 2,
  },
];

export const initialPosts: BoardPost[] = [
  {
    id: "post-1",
    boardId: "forces-in-action",
    sectionId: "push-pull",
    authorUid: "student-1",
    authorName: "Mia C.",
    authorInitials: "MC",
    caption: "The trolley only starts moving when the push is greater than the friction on its wheels.",
    visual: "visual-trolley",
    createdLabel: "8 min ago",
    commentCount: 4,
  },
  {
    id: "post-2",
    boardId: "forces-in-action",
    sectionId: "push-pull",
    authorUid: "student-2",
    authorName: "Ethan L.",
    authorInitials: "EL",
    caption: "Pulling the elastic stores energy and creates a restoring force.",
    visual: "visual-elastic",
    createdLabel: "12 min ago",
    commentCount: 2,
  },
  {
    id: "post-3",
    boardId: "forces-in-action",
    sectionId: "push-pull",
    authorUid: "student-3",
    authorName: "Chloe W.",
    authorInitials: "CW",
    caption: "The magnets push apart without touching. This is a non-contact force.",
    visual: "visual-magnets",
    createdLabel: "15 min ago",
    commentCount: 6,
  },
  {
    id: "post-4",
    boardId: "forces-in-action",
    sectionId: "friction",
    authorUid: "student-4",
    authorName: "Jayden H.",
    authorInitials: "JH",
    caption: "The rough shoe sole grips the floor and stops us from slipping.",
    visual: "visual-shoe",
    createdLabel: "19 min ago",
    commentCount: 3,
  },
  {
    id: "post-5",
    boardId: "forces-in-action",
    sectionId: "friction",
    authorUid: "student-5",
    authorName: "Noah T.",
    authorInitials: "NT",
    caption: "Brakes increase friction on the wheel rim and slow the bicycle.",
    visual: "visual-bike",
    createdLabel: "23 min ago",
    commentCount: 5,
  },
  {
    id: "post-6",
    boardId: "forces-in-action",
    sectionId: "action-reaction",
    authorUid: "student-6",
    authorName: "Sofia Y.",
    authorInitials: "SY",
    caption: "The balloon pushes air backwards, so the air pushes the balloon forwards.",
    visual: "visual-balloon",
    createdLabel: "31 min ago",
    commentCount: 7,
  },
];
